src/main/java/hudson/plugins/build_timeout/BuildTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/BuildTimeoutWrapper.java, src/main/java/hudson/plugins/build_timeout/impl/NoActivityTimeOutStrategy.java
[JENKINS-26170](https://issues.jenkins-ci.org/browse/JENKINS-26170)
`NoActivityTimeOutStrategy` slows builds as it checks logoutputs for each letters.
Using `LineTransformationOutputStream` improves the performance as it buffers outputs and processes outputs by lines.
=> [JENKINS-26170] improve the peformance of NoActivityTimeOutStrategy

src/main/java/hudson/plugins/build_timeout/BuildTimeoutWrapper.java
The `TimerTask` could be way off into the future as it is user input that
decides when this is run (and or jobs running multiple days the inactivity
could be 1 day).  Without purging the `Timer` the `TimerTask`s stay into the
queue until such time that they are the next task to run - at which time
they are removed.  But with all other triggers in a system (polling every
minute etc) added timers could stay for their maximum duration.
For arguments sake say this is 1 day and you have a build that produces
10000 lines of output every 10 hours and uses the `NoActivity` strategy.
In this case for every call to write you will have a new `TimerTask` created
that should trigger in 24hours time - it is easy to see these 10000
`TimerTask`s are referenced from the `Timer` and as such will not be …
=> [FIXED JENKINS-31627] canceled TimerTasks should be purged.

src/main/java/hudson/plugins/build_timeout/impl/ElasticTimeOutStrategy.java, src/main/resources/hudson/plugins/build_timeout/impl/ElasticTimeOutStrategy/config.jelly, src/test/java/hudson/plugins/build_timeout/impl/ElasticTimeOutStrategyJenkinsTest.java, src/test/java/hudson/plugins/build_timeout/impl/ElasticTimeOutStrategyTest.java
[JENKINS-30564](https://issues.jenkins-ci.org/browse/JENKINS-30564)
An update of #46.
* Added some tests I commented in https://github.com/jenkinsci/build-timeout-plugin/pull/46#issuecomment-151439114
* Squashed some commits in #46 . I decided to do this as:
* Commits are not bound to the JIRA issue.
* There were commits completely overridden by following commits.
* There were commits with useless comments.
|Commits in #46|New commits|
|:-------------|:----------|
|ea2bc002e9c1895cd68bbed8128d33ea49f8714d, 1555384f5914359a6352d0aaf8cc5ecbedcc8b1b, 650d8a5782dab979b65fded0650ca8b237645e4d, 2152caeb2aa1604917b9efe39c98ed2e78a98b77, a07b3f27bd36b0319c43b019aa5235e4edb4a3a6, cdcc95cc3b408d917f4edc34e0a9f6a093c90940 | 697eafc31c63c015fd5720fee762bba35fb47800| …
=> [JENKINS-30564] Failsafe timeout duration for ElasticTimeoutStrategy

src/test/java/hudson/plugins/build_timeout/impl/ElasticTimeOutStrategyTest.java
Directories like `2016-01-17_13-41-32` are created in the current working directory and not removed when running `ElasticTimeOutStrategyTest`.
It looks caused for mocked `Build` creates its root directory when instantiated.
This change creates a temporary directory in the test case, and create build directories in it.
That temporary directory is removed with `tearDown`.
=> Prevent temporary directories are left with `ElasticTimeOutStrategyTest`

src/main/resources/hudson/plugins/build_timeout/impl/LikelyStuckTimeOutStrategy/help.html
The previous help text simply referenced the source code, which isn't
helpful for most users.
=> Clarify 'likely stuck' help text.

pom.xml
[JENKINS-34846](https://issues.jenkins-ci.org/browse/JENKINS-34846)
Additional changes to #53.
=> [JENKINS-34846] Make compatible with Java5. Make tests not to run simultaneously.

pom.xml
https://jenkins.ci.cloudbees.com/job/plugins/job/build-timeout-plugin/137/
failed with following errors:
```
java.lang.Exception: Failed to initialize exploded war
Caused by: java.io.FileNotFoundException: /scratch/jenkins/workspace/plugins/build-timeout-plugin/target/jenkins-for-test/images/48x48/red_anime.gif (No such file or directory)
```
It is caused for concurrent test executions (to be exact, caused for `WarExplorer`).
As jenkins.ci.cloudbees.com overrides `concurrency` unconditionally, I have to set `forkCount` directly.
=> [JENKINS-34846] Force forkCount=1 even when concurrency is set.

src/main/java/hudson/plugins/build_timeout/BuildStepWithTimeout.java, src/main/java/hudson/plugins/build_timeout/BuildTimeOutStrategyDescriptor.java, src/main/java/hudson/plugins/build_timeout/impl/AbsoluteTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/DeadlineTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/operations/AbortOperation.java, src/main/java/hudson/plugins/build_timeout/operations/FailOperation.java, src/main/resources/hudson/plugins/build_timeout/BuildStepWithTimeout/config.jelly, src/test/java/hudson/plugins/build_timeout/BuildStepWithTimeoutTest.java, src/test/java/hudson/plugins/build_timeout/FakeBuildStep.java
Sometimes it's much better to have several small timeouts instead of one global one.
=> Add build step with timeout feature

pom.xml, src/main/java/hudson/plugins/build_timeout/BuildStepWithTimeout.java, src/main/java/hudson/plugins/build_timeout/BuildTimeOutOperation.java, src/main/java/hudson/plugins/build_timeout/BuildTimeOutOperationDescriptor.java, src/main/java/hudson/plugins/build_timeout/BuildTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/BuildTimeOutUtility.java, src/main/java/hudson/plugins/build_timeout/BuildTimeoutWrapper.java, src/main/java/hudson/plugins/build_timeout/impl/AbsoluteTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/DeadlineTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/ElasticTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/LikelyStuckTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/NoActivityTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/operations/BuildStepOperation.java, src/test/java/hudson/plugins/build_timeout/BuildStepWithTimeoutTest.java, src/test/java/hudson/plugins/build_timeout/FakeBuildStep.java
* "Jenkins" and "Plugin" get stripped from the name, so remove that and capitalize the rest.
* Update to current parent POM
* Address FindBugs warnings from new parent POM
* Update core and Java dependency to not require a dozen unused implied dependencies: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/ClassicPluginStrategy.java#L413...L427
* Remove empty Javadoc comments that just clog up the tubes.
* Add null-ness annotations
----
Tests still pass, otherwise I'm not confident I didn't mess up some of the internals. Review is needed.
=> Modernize plugin

pom.xml
This changes all URLs in pom.xml from HTTP to HTTPS so humans and machines can make sure data is encrypted in transit.
=> Use HTTPS for URLs in pom.xml

.github/release-drafter.yml
I'll make a new release to update the documentation of the plugin site (#75).
I also want to switch changelogs to github release notes using Release Drafter: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
I'm asking enabling it in https://issues.jenkins-ci.org/browse/INFRA-2463 .
=> [INFRA-2463] Add configuration for Release Drafter

pom.xml, src/main/java/hudson/plugins/build_timeout/operations/BuildStepOperation.java, src/test/java/hudson/plugins/build_timeout/impl/AbsoluteTimeOutStrategyTest.java, src/test/java/hudson/plugins/build_timeout/impl/DeadlineTimeOutStrategyTest.java, src/test/java/hudson/plugins/build_timeout/impl/ElasticTimeOutStrategyJenkinsTest.java, src/test/java/hudson/plugins/build_timeout/impl/NoActivityTimeOutStrategyTest.java, src/test/java/hudson/plugins/build_timeout/operations/AbortAndRestartOperationTest.java, src/test/java/hudson/plugins/build_timeout/operations/BuildStepOperationTest.java
[JENKINS-62275](https://issues.jenkins-ci.org/browse/JENKINS-62275)
This is using the new Jenkins.MANAGE permission. It is intended to grant an intermediate access level to global configuration for non admins but more than read users.
Enabling the BuildStep Action falls into this category so users with `Jenkins.MANAGE` should be able to configure it.
(I've also updated the the minimum Jenkins core LTS including the `Jenkins.MANAGE` and updated to a newer parent pom).
=> [JENKINS-62275] Jenkins.MANAGE has access to global config

CHANGELOG.adoc
https://issues.jenkins-ci.org/browse/INFRA-2463
Build-timeout-plugin now uses release drafter and the github release page:
https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
=> [INFRA-2463] Update CHANGELOG to point github release pages

CHANGELOG.adoc, Jenkinsfile, pom.xml
Fixes #86, plus patches the existing issues and vulnerabilities to make the upgrade work via the following:
1. Bumped Jenkins version to 2.333 for security reasons. (Needed a version that is >= 2.331 for a plugin. Otherwise there would be some vulnerability issues remained.)
2. Added minimum Java version to be 11, instead of the previous version 8. 
3. Added dependencies to make the transition from Java 8 to 11 to switch the JVM. 
4. Added plugin configurations for the upgrade while enabling the tests to be passed.
5. Added `https://repo.jenkins-ci.org/incrementals` for `incrementals` downloads. (Also to patch some vulnerability issues.)
Additionally, both the commands `mvn verfiy` then `mvn hpi:run` have been run sequentially and vulnerabilities checked to make sure everything runs …
=> Update dependencies to migrate from Java 8 to 11

.mvn/extensions.xml, .mvn/maven.config, pom.xml, src/main/java/hudson/plugins/build_timeout/impl/AbsoluteTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/DeadlineTimeOutStrategy.java
#87 was not correct. As long as the Jenkins project has not dropped support for Java 8, plugins need to be built with `<release>8</release>`, as defined in the plugin parent POM.
=> Refresh plugin build

src/main/java/hudson/plugins/build_timeout/BuildTimeOutOperation.java, src/main/java/hudson/plugins/build_timeout/BuildTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/AbsoluteTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/DeadlineTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/ElasticTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/LikelyStuckTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/NoActivityTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/operations/BuildStepOperation.java
Jenkins core has deprecated the use of JSR 305 annotations in favor of SpotBugs annotations for several core releases, and I have been slowly migrating the entire plugin ecosystem to the new set of annotations. This PR matches dozens of other PRs that have already been merged and released in other plugins to migrate to the new annotations.
=> EOL JSR 305

src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutConfiguration.java, src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutModule.java, src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutRunListener.java, src/main/java/hudson/plugins/build_timeout/global/InMemoryTimeOutStore.java, src/main/java/hudson/plugins/build_timeout/global/Lifecycle.java, src/main/java/hudson/plugins/build_timeout/global/TimeOut.java, src/main/java/hudson/plugins/build_timeout/global/TimeOutProvider.java, src/main/java/hudson/plugins/build_timeout/global/TimeOutStore.java, src/main/java/hudson/plugins/build_timeout/global/TimeOutTask.java, src/main/java/hudson/plugins/build_timeout/impl/AbsoluteTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/DeadlineTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/ElasticTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/LikelyStuckTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/impl/NoActivityTimeOutStrategy.java, src/main/resources/hudson/plugins/build_timeout/global/GlobalTimeOutConfiguration/config.jelly, src/test/java/hudson/plugins/build_timeout/global/GlobalTimeOutRunListenerTest.java, src/test/java/hudson/plugins/build_timeout/global/InMemoryTimeOutStoreTest.java, src/test/java/hudson/plugins/build_timeout/global/TimeOutTaskTest.java
This change introduces a global build time out that re-uses the existing strategies and operations. The current functionality requires users to opt-in and update the configuration of each build.
I'd like to use a global timeout to ensure builds don't run longer than the set time. Occasionally builds hang, and in large deployments it's easy for this to go unnoticed. A hanging build that goes unnoticed occupies an executor indefinitely, reducing the capacity of the system and potentially allowing the queue for a particular job to build up.
On each build:
1. Find a configured global time out
2. Schedule the configured time out operations on a dedicated ScheduledExecutorService with one thread
3. Once complete, cancel the task
Implemented with a `hudson.model.listeners.RunListener` so it can …
=> Introduce Global Time Out

pom.xml
The comment for incrementals consuming was incorrect and neither the
repository nor the pluginRepository should be specified like this.
the profile (consume-incrementals) that enables both is set in the plugin-pom and this is
enabled in this plugin using .mvn/maven.config
see https://github.com/jenkinsci/build-timeout-plugin/pull/92/files#r884975577
=> the incremental repository should not be specified.

src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutConfiguration.java, src/main/resources/hudson/plugins/build_timeout/global/GlobalTimeOutConfiguration/config.jelly
I added a checkbook to the global config to let individual jobs overwrite the global timeout, if this is enabled and the job uses a specific `BuildStepWithTimeout`. If the job does that, I assume it wants to overwrite the global timeout, otherwise it doesn't make sense in my eyes, otherwise I would just omit the step as described in this #94.
=> Let individual jobs overwrite the global timeout

pom.xml, src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutConfiguration.java
Fixes #100. 
Set the `overwriteable` variable default value to `false` regardless whether the settings is a null object or not. This should prevent excessive logging from being generated.
=> Bug fix: Fix global timeout configuration logging bug

src/main/java/hudson/plugins/build_timeout/BuildTimeOutStrategy.java, src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutConfiguration.java, src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutRunListener.java, src/main/java/hudson/plugins/build_timeout/global/TimeOutProvider.java, src/main/java/hudson/plugins/build_timeout/global/TimeOutTask.java, src/test/java/hudson/plugins/build_timeout/global/GlobalTimeOutRunListenerForAbstractProjectsTest.java
Fixes #100 
Add overloading of the `timeOutFor` method for `hudson.model.AbstractProject` in `src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutConfiguration.java` and add corresponding overloading of `setUpEnvironment` method in `src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutRunListener.java` to make sure this does nothing when we have a Matrix job or any job that is inherited from the `AbstractProject` class. Previous failed attempt to solve this include #104. This will be a more thorough treatment of the issue compared to that superficial one.
=> Fix global timeout logging for Abstract Project issue

pom.xml, src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutConfiguration.java, src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutRunListener.java, src/test/java/hudson/plugins/build_timeout/global/GlobalTimeOutRunListenerForAbstractProjectsTest.java
Third attempt to attempt to resolve #100. Got rid of the `ClassCastException` now that the `timeOutFor()` for the global timeout is overloaded for both the `AbstractProject` and `AbstractBuild` classes.
=> Third attempt at fixing logging problem for Matrix jobs

src/main/resources/hudson/plugins/build_timeout/nestedHelp.js
See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. To test this, I installed this plugin on a custom build of Jenkins that had Prototype ripped out (a local project branch), clicked on the help button for Time-out strategy, and …
=> Replace Prototype.js with native JavaScript

pom.xml, src/test/java/hudson/plugins/build_timeout/BuildStepWithTimeoutTest.java, src/test/java/hudson/plugins/build_timeout/BuildTimeoutWrapperIntegrationTest.java, src/test/java/hudson/plugins/build_timeout/global/GlobalTimeOutRunListenerTest.java, src/test/java/hudson/plugins/build_timeout/global/InMemoryTimeOutStoreTest.java, src/test/java/hudson/plugins/build_timeout/global/TimeOutTaskTest.java, src/test/java/hudson/plugins/build_timeout/impl/AbsoluteTimeOutStrategyTest.java, src/test/java/hudson/plugins/build_timeout/impl/DeadlineTimeOutStrategyTest.java, src/test/java/hudson/plugins/build_timeout/impl/ElasticTimeOutStrategyJenkinsTest.java, src/test/java/hudson/plugins/build_timeout/impl/NoActivityTimeOutStrategyTest.java, src/test/java/hudson/plugins/build_timeout/operations/AbortAndRestartOperationTest.java, src/test/java/hudson/plugins/build_timeout/operations/BuildStepOperationTest.java, src/test/java/hudson/plugins/build_timeout/operations/WriteDescriptionOperationTest.java
Hi @krisstern!
I saw #85 and thought I'd run it through the [JUnit Jupiter migration from JUnit 4.x](https://docs.openrewrite.org/recipes/java/testing/junit5/junit4to5migration) recipe on [moderne.io](https://moderne.io). This got me most of the way there, then I was able to replace almost all of the `JenkinsRule` integration tests with the JUnit 5 `WithJenkins` annotation.
The one exception is `BuildTimeoutWrapperIntegrationTest`, which is still on JUnit 4 because the `LocalData` annotation on one test does not work with JUnit 5. I think this should be easy to create another way, but didn't want to add too much more to this PR.
Ran `mvn clean verify`.
```[tasklist]
```
=> Use JUnit Jupiter

pom.xml, src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutConfiguration.java, src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutModule.java, src/main/java/hudson/plugins/build_timeout/global/GlobalTimeOutRunListener.java, src/main/java/hudson/plugins/build_timeout/global/Lifecycle.java, src/main/java/hudson/plugins/build_timeout/global/TimeOut.java
Hi!
This PR aims to modernize tooling and move this plugin to the [recommended](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/) Jenkins baseline version.
2.401.2 was the [first version to include Guice 6.x](https://www.jenkins.io/changelog-stable/#v2.401.2), which supports `jakarta.inject`.
Ran `mvn clean verify`.
```[tasklist]
```
Refs: sghill-rewrite/campaigns#1 sghill-rewrite/campaigns#2
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.jenkins.ModernizePlugin
=> Modernize to Jenkins 2.401.3 with `jakarta.inject`

src/test/java/hudson/plugins/build_timeout/operations/AbortAndRestartOperationTest.java
This plugin isn't passing with a BOM build since moving to AWS. 
When testing locally, the test:
`mvn clean -Dtest=AbortAndRestartOperationTest verify`
runs fine. However, if I change the timeout from 25 to 23, the local test fails.
My guess is that the AWS infra is running slower than the Azure infra, therefore causing the test to fail during the BOM build.
Also, it sort of makes sense that since the `once` version of the test is 25 seconds, the `twice` version of the test "should be"/"its ok" to be 50 seconds.
* `mvn clean -Dtest=AbortAndRestartOperationTest verify`
* `mvn clean verify`
=> increase the timeout so that the BOM tests pass
